version: "3.5"

services:
  basic_ec2:
    build:
      context: .
      dockerfile: ../basic_ec2_deploy/Dockerfile
    container_name: basic_ec2
    tty: true
    working_dir: /usr/src/app
    volumes:
      - ../basic_ec2_deploy/aws:/usr/src/app:cached
      - basic_ec2_node_modules:/usr/src/app/node_modules
      - ../basic_ec2_deploy/.aws:/root/.aws

volumes:
  basic_ec2_node_modules:
